// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAou26oj76pHYbcBNJClhw0UwHLoIyiu1c',
    appId: '1:566281682384:web:8fb6bd46492287bdb60dd5',
    messagingSenderId: '566281682384',
    projectId: 'cumagecedeneme',
    authDomain: 'cumagecedeneme.firebaseapp.com',
    storageBucket: 'cumagecedeneme.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHhDTPT5Y6l1yie3ZSoQVkAqvIgBG_DCQ',
    appId: '1:566281682384:android:e5dbed137220da4fb60dd5',
    messagingSenderId: '566281682384',
    projectId: 'cumagecedeneme',
    storageBucket: 'cumagecedeneme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgwqVOmmlPrQKVgeKBhZfjtTazCIf02Cs',
    appId: '1:566281682384:ios:97f36c82a64a5ac6b60dd5',
    messagingSenderId: '566281682384',
    projectId: 'cumagecedeneme',
    storageBucket: 'cumagecedeneme.firebasestorage.app',
    iosBundleId: 'com.example.cumagecedeneme1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgwqVOmmlPrQKVgeKBhZfjtTazCIf02Cs',
    appId: '1:566281682384:ios:97f36c82a64a5ac6b60dd5',
    messagingSenderId: '566281682384',
    projectId: 'cumagecedeneme',
    storageBucket: 'cumagecedeneme.firebasestorage.app',
    iosBundleId: 'com.example.cumagecedeneme1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAou26oj76pHYbcBNJClhw0UwHLoIyiu1c',
    appId: '1:566281682384:web:3b5c7f46d4b731b8b60dd5',
    messagingSenderId: '566281682384',
    projectId: 'cumagecedeneme',
    authDomain: 'cumagecedeneme.firebaseapp.com',
    storageBucket: 'cumagecedeneme.firebasestorage.app',
  );
}
